name: Linter
on: push
jobs:
  super-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Lint
        run: yarn lint