name: Build
on: push
jobs:
  build-ios:
    name: build-ios
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Bootstrap
        run: yarn bootstrap